## ----------------------------------------------------------------------------
## Script     : makefile.sources
## ----------------------------------------------------------------------------
## Author     : Johann Faerber
## Company    : University of Applied Sciences Augsburg
## ----------------------------------------------------------------------------
## Description: provide all the VHDL source files in the variable SYN_SOURCE_FILES
##              Attention !!!
##              -------------
##              Do not forget a new line after the final source file !
## ----------------------------------------------------------------------------

SYN_SOURCE_FILES = \
../../src/de1_vga_gen_rtl.vhd 
../../src/hsync_gen_rtl.vhd 
../../src/vsync_gen_rtl.vhd 
../../src/line_cnt.vhd 
../../src/pixel_cnt.vhd 
../../src/clockengen.vhd 
../../src/bild_gen_rtl.vhd

# do not delete this line
# -----------------------------------------------------------------------------
