SIM_PROJECT_NAME = dpmem
PROJECT = $(SIM_PROJECT_NAME)

# Here the VHDL files for synthesis are defined. 
SYN_SOURCE_FILES = ../../src/dpmem.vhd

# Add the toplevel fpga vhdl file
SOURCE_FILES = $(SYN_SOURCE_FILES) 

include ../makefile


