SIM_PROJECT_NAME = de1_vga_gen_rtl
PROJECT = $(SIM_PROJECT_NAME)

SOURCE_FILES = \
../../src/de1_vga_gen_rtl.vhd \
../../src/hsync_gen_rtl.vhd \
../../src/vsync_gen_rtl.vhd \
../../src/line_cnt.vhd \
../../src/pixel_cnt_rtl.vhd \
../../src/clockengen_rtl.vhd \
../../src/bild_gen_rtl.vhd

include ../makefile


